"""create task model

Revision ID: af82ae705adb
Revises:
Create Date: 2025-09-02 11:33:01.624963

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af82ae705adb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("task")
    op.add_column("task", sa.Column("name", sa.String(length=60), nullable=True))
    op.add_column(
        "task", sa.Column("description", sa.String(length=200), nullable=True)
    )
    op.add_column("task", sa.Column("created_at", sa.TIMESTAMP(), nullable=False))
    op.add_column("task", sa.Column("updated_at", sa.TIMESTAMP(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task")
